name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'src/**'
      - 'tests/**'

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt update && sudo apt install qbittorrent-nox
      - run: mkdir -p /tmp/qbittorrent-nox
      - run: ./scripts/qbittorrent.sh start /tmp/qbittorrent-nox 8080
      - run: ./scripts/pre-commit.sh
      - run: ./scripts/qbittorrent.sh stop /tmp/qbittorrent-nox

